### ISSUE TITLE
Failed to upload dSYMs using sentry-cli via fastlane

### ISSUE THREAD

**Issue by malcommac** [getsentry/sentry-fastlane-plugin#142]
### Environment

**How do you use Sentry?**
We are using self-hosted version (9.1.1)

**Which SDK and version?**
We're using:
- fastlane 2.207.0 (via gem)
- sentry-fastlane-plugin 1.12.1 (via gem)
- sentry-cli 2.3.0 (in `/usr/local/bin/sentry-cli`)

This is my portion of fastlane script, which is pretty simple btw:

```ruby
  sentry_upload_dsym(
    url: ENV["SENTRY_URL"],
    auth_token: ENV["SENTRY_AUTH_TOKEN"],
    org_slug: ENV["SENTRY_ORG_SLUG"],
    project_slug: ENV["SENTRY_PRJ_SLUG"],
    dsym_path: ENV["dSYMs_PATH"]
  )
```

All paths are correct but when executing the script I got a failure.  
That's the stacktrace.

```ruby
DEBUG [2022-07-07 09:47:26.69]: All plugins are up to date
/Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Error while calling Sentry CLI\e[0m (FastlaneCore::Interface::FastlaneError)
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-plugin-sentry-1.12.1/lib/fastlane/plugin/sentry/helper/sentry_helper.rb:46:in `block in call_sentry_cli'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/open3.rb:228:in `popen_run'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/open3.rb:210:in `popen2e'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-plugin-sentry-1.12.1/lib/fastlane/plugin/sentry/helper/sentry_helper.rb:40:in `call_sentry_cli'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-plugin-sentry-1.12.1/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:25:in `run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from /Users/macmini/builds/7221b21d/0/mobileapps/immobiliare/indomio/Indomio/fastlane/imports/dsyms.rb:41:in `_uploaddSYMsToSentryPortal'
	from /Users/macmini/builds/7221b21d/0/mobileapps/immobiliare/indomio/Indomio/fastlane/imports/dsyms.rb:13:in `uploaddSYMsToSupportedPortals'
	from Fastfile:186:in `_distribuiteBuild'
	from Fastfile:165:in `_executeCIAutomations'
	from Fastfile:110:in `block (2 levels) in parsing_binding'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/bin/fastlane:23:in `<top (required)>'
	from /Users/macmini/.gem/ruby/3.1.0/bin/fastlane:25:in `load'
	from /Users/macmini/.gem/ruby/3.1.0/bin/fastlane:25:in `<main>'
/Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Error while calling Sentry CLI (FastlaneCore::Interface::FastlaneError)
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-plugin-sentry-1.12.1/lib/fastlane/plugin/sentry/helper/sentry_helper.rb:46:in `block in call_sentry_cli'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/open3.rb:228:in `popen_run'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/open3.rb:210:in `popen2e'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-plugin-sentry-1.12.1/lib/fastlane/plugin/sentry/helper/sentry_helper.rb:40:in `call_sentry_cli'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-plugin-sentry-1.12.1/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:25:in `run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from /Users/macmini/builds/7221b21d/0/mobileapps/immobiliare/indomio/Indomio/fastlane/imports/dsyms.rb:41:in `_uploaddSYMsToSentryPortal'
	from /Users/macmini/builds/7221b21d/0/mobileapps/immobiliare/indomio/Indomio/fastlane/imports/dsyms.rb:13:in `uploaddSYMsToSupportedPortals'
	from Fastfile:186:in `_distribuiteBuild'
	from Fastfile:165:in `_executeCIAutomations'
	from Fastfile:110:in `block (2 levels) in parsing_binding'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/macmini/.gem/ruby/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/macmini/.gem/ruby/3.1.0/gems/fastlane-2.207.0/bin/fastlane:23:in `<top (required)>'
	from /Users/macmini/.gem/ruby/3.1.0/bin/fastlane:25:in `load'
	from /Users/macmini/.gem/ruby/3.1.0/bin/fastlane:25:in `<main>'
```

Looking at the source code of the plugin at line 46 of the I may imagine is something related to the input/output stream capture (`Open3.popen2e`) but nothing more.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/235645/177721590-bc6a039b-aea6-4ee8-ad06-fd904dcafdc1.png">

**Comment by emartinson** [comment]
What if I don't use self hosted sentry?
```
I'm using:
fastlane-plugin-sentry (1.20.0)
      os (~> 1.1, >= 1.1.4)

# From my ci:
 Using sentry-cli 2.28.6
 Starting sentry-cli...
[!] Error while calling Sentry CLI
```
Is there any verbose logging option?

**Comment by philipphofmann** [comment]
@emartinson, the logging is set to debug per default; we plan on adding an option to control this setting see https://github.com/getsentry/sentry-fastlane-plugin/issues/244.

**Comment by emartinson** [comment]
@philipphofmann  Thank you! What can you suggest regarding `[!] Error while calling Sentry CLI` ?

**Comment by philipphofmann** [comment]
`[!] Error while calling Sentry CLI` I need more context on this problem. Please open a new issue with more context.
